default_roles:
  - fzf
  - git
  - lazygit
  - lua
  - neovim
  - npm
  - kitty
  - sketchybar
  - skhd
  - yabai
  - tmux
  - zsh
  # - helm
  # - k8s 
  # - k9s
  # - python
  # - rust
  # - karabiner
  # - ssh
  # - sshfs
  # - terraform
  # - spotify

k8s:
  package_versions:
    default:
      - name: kubectl
      - name: kubelet
      - name: kubeadm

helm:
  repos:
    - name: traefik
      url: https://helm.traefik.io/traefik
