#!/usr/bin/env bash

# Switch to space with window running in native full-screen mode. Only works with SIP disabled.
# - key
# ctrl - 0x1B            :  index="$(yabai -m query --spaces --display | \
#                                  jq 'map(select(."is-native-fullscreen" == true))[0].index')"; \
#                           yabai -m space --focus "$index"

# # = key
# ctrl - 0x18            :  index="$(yabai -m query --spaces --display | \
#                                  jq 'map(select(."is-native-fullscreen" == true))[0].index')"; \
#                           yabai -m space --focus "$index"

