---
- name: "borders | Configure borders"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/borders"
    state: directory

- name: "borders | Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/borders"
    state: link
    force: true
- name: Start borders
  command: brew services start borders
