---
- name: "sketchybar | Configure sketchybar"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/sketchybar"
    state: directory

- name: "sketchybar | Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/sketchybar"
    state: link
    force: true
- name: Start sketchybar
  command: brew services start sketchybar
