lastupdatecheck: 1702661954
recentrepos:
- /Users/tomaskudlicka/personal/linear-cli
- /Users/tomaskudlicka/work/tetris
startuppopupversion: 5
customcommandshistory:
- q
- c
hidecommandlog: false
ignorewhitespaceindiffview: false
