#!/usr/bin/env bash
# shellcheck disable=all
CONFIG_DIR="$HOME/.config/sketchybar"
source "$HOME/.config/sketchybar/colors.sh"
source "$HOME/.config/sketchybar/icons.sh"

ITEM_DIR="$HOME/.config/sketchybar/items"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

FONT="JetBrainsMono Nerd Font"
PADDINGS=3 # All paddings use this value (icon, label, background)
SPACE_CLICK_SCRIPT="yabai -m space --focus \$SID 2>/dev/null"

# Setting up and starting the helper process
HELPER=git.felix.helper
killall helper
(cd $CONFIG_DIR/helper && make)
$CONFIG_DIR/helper/helper $HELPER > /dev/null 2>&1 &

bar=(
  height=35
  color=$BAR_COLOR
  border_width=1
  border_color=$BAR_BORDER_COLOR
  shadow=off
  position=bottom
  sticky=on
  padding_right=10
  padding_left=10
  y_offset=0
  margin=2
  topmost=window
)

sketchybar --bar "${bar[@]}"
# Setting up default values
defaults=(
  updates=when_shown
  icon.font="$FONT:Regular:14.0"
  icon.color=$ICON_COLOR
  icon.color=$ICON_COLOR
  icon.highlight_color=$HIGHLIGHT
  icon.padding_left=$PADDINGS
  icon.padding_right=$PADDINGS
  label.font="$FONT:Regular:13.0"
  label.color=$LABEL_COLOR
  label.padding_left=$PADDINGS
  label.padding_right=$PADDINGS
  padding_right=$PADDINGS
  padding_left=$PADDINGS
  background.height=20
  background.corner_radius=5
  popup.background.border_width=0
  popup.background.corner_radius=5
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=10
  popup.background.shadow.drawing=on
  scroll_texts=on
)

sketchybar --default "${defaults[@]}"

# Left
# source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
# source "$ITEM_DIR/front_app.sh"

# Center
source "$ITEM_DIR/mode_indicator.sh"

# Right
#source "$ITEM_DIR/github.sh"
#source "$ITEM_DIR/mail.sh"
source "$ITEM_DIR/time.sh"
source "$ITEM_DIR/spotify.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/slack.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/cpu.sh"

sketchybar --hotload on
############## FINALIZING THE SETUP ##############
sketchybar --update

echo "sketchybar configuation loaded.."
